# Generated by Django 4.1 on 2022-10-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_bid_listing_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_bid', to='auctions.bid'),
        ),
    ]
