# Generated by Django 4.1 on 2022-10-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_bid_identification_alter_listing_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='identification',
        ),
    ]
