# Generated by Django 4.1 on 2022-10-20 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_listing_bids_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='higher_bid_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='higher_bids_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
